### ISSUE TITLE
Fatal error when trying to add a new question

### ISSUE THREAD

**Issue by sleitao** [vfremaux/moodle-mod_flashcard#14]
Hi!
We have installed '3.5.0 (Build 2017022000)' on Moodle 3.5 using PostgreSQL 10.5, and we get the error below when trying to add a new question. We don't get the error when using MySQL.
Shouldn't the module work with PostgreSQL?

Thank you.
susana

```
Fatal error: Uncaught dml_read_exception: Erro ao ler da base de dados in /var/www/html/moodle1819/lib/dml/moodle_database.php:486 Stack trace: 
#0 /var/www/html/moodle1819/lib/dml/pgsql_native_moodle_database.php(248): moodle_database->query_end(false) 
#1 /var/www/html/moodle1819/lib/dml/pgsql_native_moodle_database.php(859): pgsql_native_moodle_database->query_end(false) 
#2 /var/www/html/moodle1819/lib/dml/moodle_database.php(1400): pgsql_native_moodle_database->get_records_sql('SELECT DISTINCT...', Array, 0, 0) 
#3 /var/www/html/moodle1819/lib/dml/moodle_database.php(1351): moodle_database->get_records_select('flashcard_card', 'WHERE flashcard...', Array, ' ORDER BY id', 'DISTINCT userid...', 0, 0) 
#4 /var/www/html/moodle1819/mod/flashcard/editview.php(62): moodle_database->get_records('flashcard_card', Array, 'id', 'DISTINCT userid...') 
#5 /var/www/html/moodle1819/mod/flashcard/view.php(272): include('/var/www/html/m...') 
#6 {main} thrown in /var/www/html/moodle1819/lib/dml/moodle_database.php on line 486
```

**Comment by JocPro** [comment]
I think it all comes down to line 62 of the editview.php file.
The sentence there doesn't make a lot of sense to me:

**$deckusers = $DB->get_records('flashcard_card', $params, 'id', 'DISTINCT userid, userid');**

As that is not compatible with Postgresql (ORDER BY must be in the SELECTed columns - in this case the ORDER BY is **'id'**) I don't know if they meant to ask for 'DISTINCT userid, id' or if the ORDER BY is meant to be 'userid'... so I went for the second choice and edited it to

**$deckusers = $DB->get_records('flashcard_card', $params, 'userid', 'DISTINCT userid, userid');**

and as far as I know (I'm currently testing it) it works. I can create cards and use them as expected.

**Comment by sleitao** [comment]
Hi JocPro,

Thank you for your input. Yes that query was problematic.
After correcting this one we had some other issues using the module with Postgrsql...

After upgrading to 2019011000 one of the issues persists:
_/var/www/html/moodle/mod/flashcard/playview.php(72): moodle_database->get_records_select('flashcard_card', 'WHERE \n flas...', Array)_ 

The problem is that Postgresql does not accept empty values.
Adding something like `if (empty($p)) $p = 0; ` on playview.php (68) will correct the issue on PostgreSQL.

**Comment by vfremaux** [comment]
Your change proposals have been reported in the flashcard code for branches >= 35.

Thanks for your contribution. It helps to make the plugin more compatible indeed. 

Cheers !
