### ISSUE TITLE
Update to new version causes error

### ISSUE THREAD

**Issue by germanvaleroelizondo** [vfremaux/moodle-mod_flashcard#17]
When upgrading to the new versiontoday, I got the following error:

Warning: require_once(/Warning: require_once(/var/www/html/lib/eventslib.php): failed to open stream: No such file or directory in /var/www/html/mod/flashcard/lib.php on line 29): failed to open stream: No such file or directory in /var/www/html/mod/flashcard/lib.php on line 29

I can not create a new empty lib\eventslib.php file today.
I can not  comment out line 29 in lib.php.

 I will need to ask the IT guys at my University tomorrow.

Paul Powell wrote on 8 January 2019, 04:31 "Installed this for 3.6 today and it causes a nasty whitescreen for the whole site. This is due to /lib/eventslib.php being required by lib.php. Commenting out this line (29 in lib.php) gets it working. Furthermore, another (less serious) error is caused by line 170 of renderer.php. This stops the user overview from being displayed. $OUTPUT->pix_icon needs changing to $this->output->pix_icon."

**Comment by vfremaux** [comment]
Hi German, what branch are you using ?

Valery

Le dim. 17 févr. 2019 à 18:01, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
Modflashcard 3.5.0 (Build 2019011000) 2018120600
in a server with Moodle 3.6.2+ (Build: 20190118)

**Comment by germanvaleroelizondo** [comment]
Hi Valery,

The IT guy at my University commented out the line described and the server works again.

But I fear many more Moodlers might suffer from the same problem.

**Comment by vfremaux** [comment]
Hi german

this is indeed a version incompatibiity :
lib/eventslib.php has disappeared in moodle 3.6 so the only match for
flashcard over 3.6.1 is the MOODLE_36_STABLE branch

Cheers
Valery

Le lun. 18 févr. 2019 à 15:37, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
Hi Valery,
The current problem is:
A new empty Moodle 3.6 server,
when I install from the Moodle plugins database, choosig the version for Moodle 3.6, it causes a white screen freeze.

![install flashcard from moodle plugins database for m36](https://user-images.githubusercontent.com/2671923/53030003-a4881600-342f-11e9-87b3-70d10a6cb482.png)

**Comment by vfremaux** [comment]
hi German

I renewed the 3.6 zip in moodle.org. Something in my production process
seems going wrong when a new master branch is being handled and the last
branch zip
seems NOT reflecting the reference code.

This is fixed for flashcard, at least synced to dev stable version.

cheers
Valery

Le mar. 19 févr. 2019 à 17:18, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
Hi Valery,

Do you know when will the Moodle plugins database have the right versions ?

**Comment by vfremaux** [comment]
I have dropped the zip yesterday.

Cheers
Valery

Le mar. 19 févr. 2019 à 17:31, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
I installed from Moodle plugins database,

but I got $plugin->version  = 2019011000;  // The current module version (Date: YYYYMMDDXX): 

Warning: require_once(C:\Temp\m_3_6_2_plus\server\moodle/lib/eventslib.php): failed to open stream: No such file or directory in C:\Temp\m_3_6_2_plus\server\moodle\mod\flashcard\lib.php on line 29

Fatal error: require_once(): Failed opening required 'C:\Temp\m_3_6_2_plus\server\moodle/lib/eventslib.php' (include_path='C:\Temp\m_3_6_2_plus\server\moodle/lib/pear;C:\Temp\m_3_6_2_plus\server\php\PEAR') in C:\Temp\m_3_6_2_plus\server\moodle\mod\flashcard\lib.php on line 29

**Comment by germanvaleroelizondo** [comment]
SO, the problem is that the Moodle plugins database by default will offer the 3.5 version only for 3.5.

It should instead offer a version for all supported Moodle branches. See https://moodle.org/plugins/atto_cloze 

![bad versions offered](https://user-images.githubusercontent.com/2671923/53291396-2782d680-3778-11e9-94db-6d64e57680f8.png)

![good versions offered](https://user-images.githubusercontent.com/2671923/53291398-2ce02100-3778-11e9-9f44-991c020481cc.png)

**Comment by vfremaux** [comment]
Actually i don't know what provoques the difference in exposing the
plugin..

as all the versions are updated in the "Versions"  panel

my guess is that the front panel of the plugin exposure only presents the
most recent update, and the versions attached to it. So if you update the
3.5 branch with a bugfiwed package,
it seems this version will come up to the front download proposal.

I don't think i can do lot for that...

Cheers
Valery



Le sam. 23 févr. 2019 à 21:34, Germán Valero <notifications@github.com> a
écrit :

**Comment by vfremaux** [comment]
I think you need explicitely get the 36 branch version to avoid this. did
you ?

Valery

Le sam. 23 févr. 2019 à 21:09, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
I did choose the 3.6 version.

I just saw the exact same wrong behabiour with the new trema theme at https://moodle.org/plugins/theme_trema.

When I try to install from the Moodle plugins database in my 3.6.2 server, it downloads the 3.5 version.

Maybe we should contact David Mudrak, as this issue now affects several plugins ?

**Comment by vfremaux** [comment]
i think you can indeed, if u are using the embedded plugin manager tools.
This might be a mispreparation of the moodle side plugins API. This could
be fine it be reporter indeed.
Cheers
Valery

Le sam. 2 mars 2019 à 15:48, Germán Valero <notifications@github.com> a
écrit :

**Comment by germanvaleroelizondo** [comment]
I just posted on the Moodle developer forum at https://moodle.org/mod/forum/discuss.php?d=383331.

**Comment by germanvaleroelizondo** [comment]
I have finally figured it out.
Silly old me :(
Problem solved, issue closed.

See https://moodle.org/mod/forum/discuss.php?d=383331#p1550506
